# Generated by Django 4.2 on 2023-04-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_date_joined'),
        ('studio', '0002_alter_studio_phone_number'),
        ('authentication', '0003_alter_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='user',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
    ]
