# Generated by Django 4.2 on 2023-04-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_studio_phone_number'),
        ('student', '0007_alter_student_date_joined'),
        ('authentication', '0004_user_student_user_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.studio'),
        ),
    ]
