# Generated by Django 4.2 on 2023-04-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_student_alter_user_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='studio',
        ),
    ]
