# Generated by Django 4.2 on 2023-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes_remaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class_package',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
