# Generated by Django 4.2 on 2023-04-20 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_classes_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
