# Generated by Django 4.2 on 2023-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_date_joined_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class_package',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
