# Generated by Django 4.2 on 2023-04-25 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_current_class_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
