# Generated by Django 4.2 on 2023-05-01 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='last_class_taken',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
