# Generated by Django 4.2 on 2023-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_status_student_last_class_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_current',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_class_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
