# Generated by Django 4.2 on 2023-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_account_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='account_current',
        ),
        migrations.AddField(
            model_name='student',
            name='last_payment',
            field=models.DateField(blank=True, default='2001-01-01', null=True),
        ),
    ]
