# Generated by Django 4.2 on 2023-05-03 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_classes_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_last_resolved',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
