# Generated by Django 4.2 on 2023-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_payment_last_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_last_resolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
