# Generated by Django 4.2 on 2023-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_package', '0003_alter_classes_stripe_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='number_of_classes_included_in_package',
            field=models.CharField(blank=True, default='Unlimited', max_length=255, null=True),
        ),
    ]
